### PR TITLE
Add targets for parcel and webpack compatibility

### PR DESCRIPTION
**Pull request by jpflueger**
This changeset contains some fixes for consuming this package as a library.

## `package.json#main` entry for Webpack
Setting this field will allow Webpack consumers to use the stylesheets more fluidly, like this:

```
@import '@fermyon/styleguide';
```

where before they would need to provide the full path like:

```
@import '@fermyon/styleguide/scss/fermyon.scss';
```

Additionally, `package.json#targets.main` is set to false so Parcel ignores it because Parcel expects the main entry to be a CommonJS module.

## Parcel Targets
I also added two targets for Parcel bundling of this project. One target will bundle the main docs page and another target will bundle the SASS as CSS. This shouldn't change existing functionality except that the `styles` and `watch` scripts no longer seem necessary because the `dev` script will automatically watch for changes to the SCSS files and hot reload accordingly.

## SCSS image path variable
Added variable to override default relative path root because `scss/fermyon-response.scss` uses a relative url import of `image/avatar.png`. In bundlers like webpack and parcel, relative paths are assumed to be relative to entry file being bundled. Before this change, a consumer would need to copy the avatar image into a directory relative to their entry file. Now a consumer can adjust this for their bundler like:

```
$image-base-path: '../node_modules/@fermyon/styleguide/image';
@import '@fermyon/styleguide/scss/fermyon.scss';
```

And the bundler with automatically find and copy the avatar image to their dist folder.

## Optimizing CSS
By default, the previous command `parcel build scss/fermyon.scss --dist-dir css` did not optimize the output CSS file. I preserved this functionality by setting `package.json#targets.css.optimize` to false. Though I do think that allowing the optimization to happen could be beneficial for consumers of the stylesheets. Thoughts on enabling optimization for CSS output?

Signed-off-by: Justin Pflueger <justin.pflueger@fermyon.com>

### CODE REVIEW

**Comment by jpflueger** [comment]
@flynnduism it looks like netlify might not have access to my fork? Not sure how to fix it but in my local testing the parcel builds do seem to work.

**Comment by flynnduism** [comment]
The logs were weird - there's nothing about this PR / branch setup that should fail like this...

I disconnected and re-connected the Netlify app permissions from GH and have re-run the checks, re-trying now

**Comment by jpflueger** [comment]
Searching around, it seems like it might be because netflify doesn't have access to my fork. I'm going to push a new PR with a branch on this repo to see if it changes the output.

**Comment by jpflueger** [comment]
Closing this one in favor of #39

**Pull request closed without merging**
